services:    

  crm-server:
    container_name: crm-server
    image: node:20-alpine3.19        
    working_dir: /opt/server
    volumes:
      - ./crm-server:/opt/server                   
    command: npm run start
    
  crm.demo.ru:
    container_name: crm.demo.ru        
    image: nginx:1.27.0-alpine3.19-slim        
    volumes:
      - ./crm-frontend/nginx:/etc/nginx/conf.d
      - ./crm-frontend/www:/var/www

  attacker.demo.ru:
    container_name: attacker.demo.ru
    image: nginx:1.27.0-alpine3.19-slim
    volumes:
      - ./attacker/nginx:/etc/nginx/conf.d
      - ./attacker/www:/var/www
    
  metrics.demo.ru:
    container_name: metrics.demo.ru
    image: nginx:1.27.0-alpine3.19-slim
    volumes:
      - ./metrics/nginx:/etc/nginx/conf.d
      - ./metrics/www:/var/www
  
  nginx:
    container_name: nginx
    image: nginx:1.27.0-alpine3.19-slim        
    ports:
      - 80:80        
    volumes:
      - ./nginx:/etc/nginx/conf.d      
    depends_on:      
      - crm.demo.ru
      - attacker.demo.ru
      - metrics.demo.ru 
            
volumes:
  crm-volume:
    external: false
    
networks:
  crm-network:
    driver: bridge